### ISSUE TITLE
localtime 오류

### ISSUE THREAD

**Issue by 178kg78cm** [KW-2024SoftwareEngineering/Project2#27]

**Comment by N-jongsik** [comment]
오류 해결 확인해써요

**Comment by 178kg78cm** [comment]
localtime에서 문제 생기는 거 같은데 정확하게 모르겠다

**Comment by syoooooung** [comment]
localtime함수를 호출해서 time2에게 값을 줄 때 time1도 같이 바뀌네요

**Comment by swjsh19** [comment]
time2에게 값을 줄 때 time1도 바뀌는데, 그 반대의 경우는 또 안되네요.

**Comment by N-jongsik** [comment]
text1이랑 text2시간 직접 찍어봐서 출력해봤는데 똑같이 나오네요,,,

**Comment by syoooooung** [comment]
local time이 정적 변수로 포인터를 반환하고 time1과 time2가 모두 동일한 정적 변수를 참조하는게 문제인 것 같아요. localtime 대신 localtime_r를 써볼까요?

**Comment by 178kg78cm** [comment]
지금 적용 중입니다.

**Comment by 178kg78cm** [comment]
해결했습니다.
